### PR TITLE
ubuntu: drop more unneeded packages 

### PR DESCRIPTION
**Pull request by syuu1228**
This remove more unneeded packages on Ubuntu image, includes:
- accountsservice
- udisks2
And also disable polkit.service by default since it almost unneeded but some CLI commands requires that, so let D-Bus to autostart the service when the API invoked.

### CODE REVIEW

**Comment by syuu1228** [comment]
test passed: https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/ami/1328/

**Comment by syuu1228** [comment]
Rebased with next

**Comment by yaronkaikov** [comment]
@syuu1228 i ran https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/next-machine-image/386/ and it's failing (from your branch)

**Comment by syuu1228** [comment]
Fixed the bug, and jenkins test passed:
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/next-machine-image/451/

**Comment by syuu1228** [comment]
@yaronkaikov ping

**Pull request merged**
