### PR TITLE
Feature: Azure image support

### PR DESCRIPTION
**Pull request by yaronkaikov**
As we want to be able to support additional cloud provides, we be able creating Scylla machine image on Microsoft Azure platform
As first step, let's build Scylla Azure image with Packer tool
(refernce: https://microsoft.github.io/AzureTipsAndTricks/blog/tip201.html)

Need to get https://github.com/scylladb/scylla/pull/7807 merged before

Fixes: https://github.com/scylladb/scylla-machine-image/issues/54

### CODE REVIEW

**Comment by fruch** [comment]
@yaronkaikov should be a PR on scylla core ? and not just an issue ?

also can you provide us with example of this image ? so people can manually run it ? (i.e. we do have a big effort to actually have a test for such image)

**Comment by yaronkaikov** [comment]
@fruch I have updated the description, there is a PR and it's in draft

**Review by penberg — APPROVED** [review]
lgtm

**Review by syuu1228 — APPROVED** [review]
LGTM

**Pull request merged**
