### PR TITLE
Revert "aws: switch AMI distribution to Amazon Linux 2"

### PR DESCRIPTION
**Pull request by syuu1228**
This reverts commit de1bb48faf75fc2edbfa83dc9108d69217476a21.

We have problem on Amazon Linux kernel on scylladb/scylla#7607, have to
moving back to CentOS7.

### CODE REVIEW

**Comment by fruch** [comment]
@slivne just to clearify, we are reverting master and backport to 4.3 ?
or we want it directly/only on 4.3 ?

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
passed OSS next, I've backported to next-4.3

**Comment by penberg** [comment]
@fruch We want to revert this in master, and then backport, like we always do. The plan is to move master to CentOS 8 for 4.4.

**Comment by fruch** [comment]
> @fruch We want to revert this in master, and then backport, like we always do. The plan is to move master to CentOS 8 for 4.4.

this is the way (just wanted to clarify, since there were case we skipped master, cause of reasons)
@slivne already answered me last night

**Comment by syuu1228** [comment]
@penberg @fruch Here's CentOS8 support for master branch: https://github.com/scylladb/scylla-machine-image/pull/87

**Pull request merged**
