### PR TITLE
[Azure]:fix coredump installation failure

### PR DESCRIPTION
**Pull request by yaronkaikov**
Error message:
```
15:46:12  �[1;31m==> azure: E: Unable to locate package systemd-coredump�[0m
15:46:13  �[1;31m==> azure: Traceback (most recent call last):�[0m
15:46:13  �[1;31m==> azure:   File "/home/azureuser/scylla_install_image", line 80, in <module>�[0m
15:46:13  �[1;31m==> azure:     run('apt-get install -y systemd-coredump', shell=True, check=True)�[0m
15:46:13  �[1;31m==> azure:   File "/usr/lib/python3.8/subprocess.py", line 516, in run�[0m
15:46:13  �[1;31m==> azure:     raise CalledProcessError(retcode, process.args,�[0m
15:46:13  �[1;31m==> azure: subprocess.CalledProcessError: Command 'apt-get install -y systemd-coredump' returned non-zero exit status 100.�[0m
15:46:13  �[1;32m==> azure: Provisioning step had errors: Running the cleanup provisioner, if present...�[0m
```

Closes: https://github.com/scylladb/scylla-pkg/issues/3011

### CODE REVIEW

**Comment by yaronkaikov** [comment]
@syuu1228 does it make sense that this change solves the coredump issue ?
Verified with:
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/271/
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/272/
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/273/
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/274/
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/275/

And they all passed

**Comment by fruch** [comment]
Is systemd-coredump depended on apport ? and even then this doesn't sound like fix of anything.

I would start with printing the actual failure from the install commands

**Comment by yaronkaikov** [comment]
@fruch It doesn't make sense but, in fact.. with this change `systemd-coredump` installation passing every time..
How should we print the actual failure?

**Comment by fruch** [comment]
> @fruch It doesn't make sense but, in fact.. with this change `systemd-coredump` installation passing every time.. How should we print the actual failure?

I've seen the backtrace, now I see the full log, and that it say it doesn't find the package.
as @syuu1228 mentioned sound like a timing issue, which might mean so code is running in the background using apt or clearing it's cache.

adding apt-get update before the command would probably address it too, but not fix the root cause.

cloud be that we are not waiting correctly for cloud-init to finish ? since cloud init can mock with the apt lists based on the cloud region (like I've seen on AWS)

**Comment by fruch** [comment]
> > @fruch It doesn't make sense but, in fact.. with this change `systemd-coredump` installation passing every time.. How should we print the actual failure?
> 
> I've seen the backtrace, now I see the full log, and that it say it doesn't find the package. as @syuu1228 mentioned sound like a timing issue, which might mean so code is running in the background using apt or clearing it's cache.
> 
> adding apt-get update before the command would probably address it too, but not fix the root cause.
> 
> cloud be that we are not waiting correctly for cloud-init to finish ? since cloud init can mock with the apt lists based on the cloud region (like I've seen on AWS)

and yeah we wait for cloud-init only for AWS:

https://github.com/scylladb/scylla-machine-image/blob/106dc6d8c15f597af1881cee5f3bee46c612d2c1/packer/scylla.json#L172

**Comment by yaronkaikov** [comment]
> > > @fruch It doesn't make sense but, in fact.. with this change `systemd-coredump` installation passing every time.. How should we print the actual failure?
> > 
> > 
> > I've seen the backtrace, now I see the full log, and that it say it doesn't find the package. as @syuu1228 mentioned sound like a timing issue, which might mean so code is running in the background using apt or clearing it's cache.
> > adding apt-get update before the command would probably address it too, but not fix the root cause.
> > cloud be that we are not waiting correctly for cloud-init to finish ? since cloud init can mock with the apt lists based on the cloud region (like I've seen on AWS)
> 
> and yeah we wait for cloud-init only for AWS:
> 
> https://github.com/scylladb/scylla-machine-image/blob/106dc6d8c15f597af1881cee5f3bee46c612d2c1/packer/scylla.json#L172

@fruch Please review

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
would still check it with GCE, but I don't think it should break anything...

**Comment by yaronkaikov** [comment]
Verification:
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/291/
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/290/
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/289/
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/288/

https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/gce-image/636/

https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/ami/1497/

**Comment by yaronkaikov** [comment]
> Verification: https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/291/ https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/290/ https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/289/ https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/azure-image/288/
> 
> https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/gce-image/636/
> 
> https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/ami/1497/

@fruch already did

**Comment by yaronkaikov** [comment]
Backport to 5.0 - done

**Comment by yaronkaikov** [comment]
Backported to 2022.1

**Pull request merged**
