### PR TITLE
aws: on Ubuntu AMI, remove auto update features by default

### LINKED ISSUE #152: Unattended upgrades enabled by default
When additional software is installed on Ubuntu-based Scylla machine images, one may hit the following problem:

```
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 15976 (unattended-upgr)
```

Are unattended upgrades enabled by default due to some reason? What is the recommended way to disable it?

### PR DESCRIPTION
**Pull request by syuu1228**
We don't want to enable auto update features on our ami, remove
unattended-upgrades and update-notifier-common to disable them.

fixes #152

### CODE REVIEW

**Comment by slivne** [comment]
@adambabik / @nuivall / @carlosms this is the patch - still under review

**Review by adambabik — DISMISSED** [review]
Looks good but it's hard to tell if it will work as expected. How was it tested?

Our workaround for now is disabling the `unattended-upgrades` service.

**Review by penberg — APPROVED** [review]
Looks good to me. @syuu1228 can you comment on how this was tested?

**Comment by syuu1228** [comment]
> Looks good but it's hard to tell if it will work as expected. How was it tested?
> 
> Our workaround for now is disabling the `unattended-upgrades` service.

Correct, I realized that even after we set the APT config value, unattended-upgrades service is still running and seems like do something.
I think better solution is completely remove these auto update features.
So I pushed new version, that removes `unattended-upgrades update-notifier-common` packages.

After removed them, no unattended-upgrades service running.
It sill run apt-daily.timer / apt-daily-upgrade.timer but the service do nothing because APT::Periodic::Enable set to null since we removed all config files for APT::Periodic.
(the behavior defined at line 532 of /usr/lib/apt/apt.systemd.daily, tested with `sh -x`)

**Pull request merged**
