### PR TITLE
move cloud related code from scylla repository to scylla-machine-image

### PR DESCRIPTION
**Pull request by syuu1228**
Currently, cloud related code have cross-dependencies between
scylla and scylla-machine-image.
It is not good way to implement, and single change can break both
package.
To resolve the issue, we need to move all cloud related code to
scylla-machine-image, and remove them from scylla repository.

Here's change list:
 - move cloud part of scylla_util.py to lib/scylla_cloud.py
 - move cloud part of scylla_io_setup to common/scylla_cloud_io_setup
 - move scylla_ec2_check to common/
 - merge scylla_bootparam_setup to packer/scylla_install_image

---- 

This is scylla-machine-image part of the PR, please merge this part first.

### CODE REVIEW

**Comment by syuu1228** [comment]
Scylla part is at https://github.com/scylladb/scylla/pull/9957

**Comment by syuu1228** [comment]
Unlike scylla_ec2_check, I did not copied scylla_bootparam_setup to common/, I merged it into packer/scylla_install_image.
Because it is only required on image building time, and scylla_install_image already trying to modify boot parameter.
Also, I found that current code is failing to change boot parameter on Ubuntu 20.04.
Because we need to edit /etc/default/grub.d/50-cloudimg-settings.cfg instead of /etc/default/grub on this distro.
So fixed the issue in this PR.

**Comment by syuu1228** [comment]
@yaronkaikov @avikivity I confused with the license in scylla-machine-setup scripts.
It seems all scripts has Apache-2.0 license, not AGPL3.

I added new scripts in this PR, such as scylla_cloud_io_setup. The code in this script is moved from scylla_io_setup which is in scylla repo, and it is licensed with AGPL.
Which license should we apply to this, AGPL or Apache-2.0?

**Comment by avikivity** [comment]
Code moved to scylla-machine-image should be relicensed to Apache License 2.0.

**Comment by syuu1228** [comment]
> Code moved to scylla-machine-image should be relicensed to Apache License 2.0.

Okay, two script licenses were not changed from AGPL, just changed them to Apache-2.0.

**Comment by yaronkaikov** [comment]
@syuu1228 You can verify your changes (for both Scylla and machine-image) by re-building https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/byo_build_tests_dtest/1364/ , it also create an AMI image

**Review by yaronkaikov — APPROVED** [review]

**Comment by syuu1228** [comment]
@yaronkaikov Can we merge this now?

**Comment by yaronkaikov** [comment]
@syuu1228 I created an AMI based on both branches you have (scylla and machine-image). https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/byo_build_tests_dtest/1373/consoleFull 

And created an instance based on the AMI i have created. Instance ID:`i-0ad1282d2d9836949`
Scylla is running without any issues. so i assume it's all good. Do you want to have a look to verify we are not missing anything? The instance is currently off. so you can just turn it on.
Let me know, from my POV we can merge it

**Comment by syuu1228** [comment]
@yaronkaikov I think we can merge it now.

**Pull request merged**
