### PR TITLE
scylla_cloud.py: import missing 'glob' module

### LINKED ISSUE #294: scylla_cloud.py doesn't import glob
```
Feb 01 14:51:56 artifacts-gce-image-jenkins-db-node-8ab79bc2-0-1 scylla_image_setup[984]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_create_devices", line 113, in <module>
Feb 01 14:51:56 artifacts-gce-image-jenkins-db-node-8ab79bc2-0-1 scylla_image_setup[984]:     disk_devices = get_default_devices(instance)
Feb 01 14:51:56 artifacts-gce-image-jenkins-db-node-8ab79bc2-0-1 scylla_image_setup[984]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_create_devices", line 85, in get_default_devices
Feb 01 14:51:56 artifacts-gce-image-jenkins-db-node-8ab79bc2-0-1 scylla_image_setup[984]:     disk_names = instance.getEphemeralOsDisks()
Feb 01 14:51:56 artifacts-gce-image-jenkins-db-node-8ab79bc2-0-1 scylla_image_setup[984]:   File "/opt/scylladb/scylla-machine-image/lib/scylla_cloud.py", line 133, in getEphemeralOsDisks
Feb 01 14:51:56 artifacts-gce-image-jenkins-db-node-8ab79bc2-0-1 scylla_image_setup[984]:     return self.os_disks[self.EPHEMERAL]
Feb 01 14:51:56 artifacts-gce-image-jenkins-db-node-8ab79bc2-0-1 scylla_image_setup[984]:   File "/opt/scylladb/scylla-machine-image/lib/scylla_cloud.py", line 125, in os_disks
Feb 01 14:51:56 artifacts-gce-image-jenkins-db-node-8ab79bc2-0-1 scylla_image_setup[984]:     disks_present = self._non_root_disks()
Feb 01 14:51:56 artifacts-gce-image-jenkins-db-node-8ab79bc2-0-1 scylla_image_setup[984]:   File "/opt/scylladb/scylla-machine-image/lib/scylla_cloud.py", line 114, in _non_root_disks
Feb 01 14:51:56 artifacts-gce-image-jenkins-db-node-8ab79bc2-0-1 scylla_image_setup[984]:     disks_present = list(filter(disk_re.match, glob.glob("/dev/sd*")))
Feb 01 14:51:56 artifacts-gce-image-jenkins-db-node-8ab79bc2-0-1 scylla_image_setup[984]: NameError: name 'glob' is not defined
```

* db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/8ab79bc2-0426-4d43-9bc5-b24861ced0af/20220201_145945/db-cluster-8ab79bc2.tar.gz
* sct - https://cloudius-jenkins-test.s3.amazonaws.com/8ab79bc2-0426-4d43-9bc5-b24861ced0af/20220201_145945/sct-runner-8ab79bc2.tar.gz
* https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-gce-image-test/379/

### PR DESCRIPTION
**Pull request by syuu1228**
This fixes "NameError: name 'glob' is not defined" error.

Fixes #294

### CODE REVIEW

**Review by fruch — DISMISSED** [review]
LGTM

**Comment by fruch** [comment]
@syuu1228 now that you have move code in this repo, I would advise extending the unit tests to cover it, right now they are mocking it away. (Cause it wasn't part of this code base)

**Comment by yaronkaikov** [comment]
@syuu1228 Please rebase so we can merge

**Comment by syuu1228** [comment]
@yaronkaikov rebased

**Review by yaronkaikov — APPROVED** [review]

**Comment by bentsi** [comment]
@fruch agree. 
@syuu1228 all the PRs that touch Python code should have unit tests! Once we release and have less pressure we need to improve coverage

**Comment by syuu1228** [comment]
> @fruch agree. 
> 
> @syuu1228 all the PRs that touch Python code should have unit tests! Once we release and have less pressure we need to improve coverage

Okay, I will send unit tests for newly added python codes.
I probably also need to do same in scylla main repo, too.

**Pull request merged**
