### PR TITLE
[images] build based on ubuntu24.04

### PR DESCRIPTION
**Pull request by yaronkaikov**
As part of our work in scylladb/scylla-enterprise#4111

Updating our Images to the latest LTS Ubuntu

Also include a minor syntax fix - 9a642d3e79d0f6c20d0839e7c0bb5c897606dcb9

Fixes: scylladb#527

### CODE REVIEW

**Comment by yaronkaikov** [comment]
Verified with https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/next-machine-image/367/

**Review by syuu1228 — APPROVED** [review]
LGTM

**Review by Annamikhlin — APPROVED** [review]
LGTM
just don't forget to fixup the `wip` before the merge :)

**Comment by yaronkaikov** [comment]
@fruch this is ready for merge, please advise about the performance rests you did as part of https://github.com/scylladb/qa-tasks/issues/1729, if the results are better/the same let's merge it

/cc @mykaul

**Comment by yaronkaikov** [comment]
Based on https://github.com/scylladb/qa-tasks/issues/1729#issuecomment-2231083515, it seems we are good to go

@mykaul

**Pull request merged**
