### PR TITLE
Add missing i4g.4xlarge instnace type

### PR DESCRIPTION
**Pull request by yaronkaikov**
Adding pre-configure io_setup values
Also since `i4g` doesn't support enhanced networking adding it to use ENA

### CODE REVIEW

**Comment by Annamikhlin** [comment]
Please check if you need to remove the `i4g.large` type, if it not should be supported 
https://github.com/scylladb/scylla-machine-image/blob/a5c370764b976059a089e888b849115504a1c8ee/common/scylla_cloud_io_setup#L296-L300

**Comment by yaronkaikov** [comment]
> Please check if you need to remove the `i4g.large` type, if it not should be supported
> 
> https://github.com/scylladb/scylla-machine-image/blob/a5c370764b976059a089e888b849115504a1c8ee/common/scylla_cloud_io_setup#L296-L300

We should support it as well. so keeping it

**Comment by Annamikhlin** [comment]
> > Please check if you need to remove the `i4g.large` type, if it not should be supported
> > https://github.com/scylladb/scylla-machine-image/blob/a5c370764b976059a089e888b849115504a1c8ee/common/scylla_cloud_io_setup#L296-L300
> 
> We should support it as well. so keeping it

So we are supporting it but not testing it?

**Comment by Annamikhlin** [comment]
> > > Please check if you need to remove the `i4g.large` type, if it not should be supported
> > > https://github.com/scylladb/scylla-machine-image/blob/a5c370764b976059a089e888b849115504a1c8ee/common/scylla_cloud_io_setup#L296-L300
> > 
> > 
> > We should support it as well. so keeping it
> 
> So we are supporting it but not testing it?

Ok, I see your answer in https://github.com/scylladb/scylla-pkg/pull/3556#discussion_r1309918566 :)

**Review by Annamikhlin — APPROVED** [review]
lgtm

**Review by benipeled — APPROVED** [review]

**Comment by yaronkaikov** [comment]
Verified with https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-ami-arm-test/71/

**Pull request merged**
