### PR TITLE
fix(license): adding license information on all relevant files

### PR DESCRIPTION
**Pull request by bentsi**
Added license headers to the relevant files

### CODE REVIEW

**Comment by fruch** [comment]
@bentsi this is enough ? or we still need the license as part of the RPM ?

**Comment by fruch** [comment]
@bentsi, I think we should start merging into next from now on

**Comment by bentsi** [comment]
OK. @fruch Is there any automated process that merges next to master?

**Comment by fruch** [comment]
yes, the next pipeline is doing (should be) that, we gave the right permission to the scylla-promoter

**Comment by bentsi** [comment]
> @bentsi this is enough ? or we still need the license as part of the RPM ?

updated the PRM package license

**Comment by slivne** [comment]
@avikivity ping we want this merged before the branching

**Comment by bentsi** [comment]
@avikivity @penberg  :ping_pong:

**Comment by slivne** [comment]
@penberg / @avikivity please review - this is blocking 4.0

**Comment by slivne** [comment]
@penberg - you have been chosen - please review and merge.

**Comment by penberg** [comment]
Queued to next as f21be0fde0e26039dde07c05bf78dcd3cdf00f64.

**Pull request closed without merging**
