### PR TITLE
build.yml: fix git permission bug for checkout dir

### PR DESCRIPTION
**Pull request by yaronkaikov**
github action is failing with the following error:
```
fatal: unsafe repository ('/scylla-machine-image' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /scylla-machine-image
fatal: unsafe repository ('/scylla-machine-image' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /scylla-machine-image
Error: Process completed with exit code 128.
```

### CODE REVIEW

**Comment by benipeled** [comment]
How subnet-base-arch will help us solve/investigate the capacity "issue"?

**Comment by yaronkaikov** [comment]
> How subnet-base-arch will help us solve/investigate the capacity "issue"?

It will not, this is a solution for now so it will work. we will need to find a way to check the actual availability before, i will open an issue for that

**Comment by yaronkaikov** [comment]
> > How subnet-base-arch will help us solve/investigate the capacity "issue"?
> 
> It will not, this is a solution for now so it will work. we will need to find a way to check the actual availability before, I will open an issue for that

The default subnet_id we were using until today was us-east-1b which is not good for `aarch64` (at the moment at least)

**Comment by benipeled** [comment]
> > How subnet-base-arch will help us solve/investigate the capacity "issue"?
> 
> It will not, this is a solution for now so it will work. we will need to find a way to check the actual availability before, i will open an issue for that

I got confused - is there going to be a follow-up change? so why not add them together?

> The default subnet_id we were using until today was us-east-1b which is not good for aarch64 (at the moment at least)

The capacity issue at the moment, is with AZ A but it can be changed to AZ B in a few minutes/hours/days

**Comment by fruch** [comment]
docs says you dont have to specify zone, or subnet...
https://developer.hashicorp.com/packer/plugins/builders/amazon/instance#availability_zone

**Comment by yaronkaikov** [comment]
dropping the changes related to the subnet configuration. Let's see if waiting will actually solve the issue. 
In parallel i will look for better solution

**Comment by yaronkaikov** [comment]
@fruch Please review

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
> @fruch Please review

seems like the rocky8 image got the newer git version as well

**Pull request merged**
