### PR TITLE
packer/build_deb_image.sh: align tags

### PR DESCRIPTION
**Pull request by yaronkaikov**
As a preparation for https://github.com/scylladb/scylla-pkg/issues/2616, setting label creation during the actuall image build (for all vendors)

### CODE REVIEW

**Review by fruch — DISMISSED** [review]
LGTM

**Comment by yaronkaikov** [comment]
Verified: 
AMI: https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/ami/1131/
Azure: https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/azure-image/138/
Gce: https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/gce-image/525/

**Comment by yaronkaikov** [comment]
@fruch I have added the arch to image name (for AMI only)

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
