### PR TITLE
aws: chown skel files to scyllaadm:scyllaadm

### LINKED ISSUE #125: scyllaadm user files are with root:root permissions needs to be updated
file aws/ami/files/scylla_install_ami

```
    run('ln -sf /home/scyllaadm {}'.format(homedir))
    for skel in glob.glob('/etc/skel/.*'):
        if not skel.endswith('.bash_profile'):
            shutil.copy(skel, '/home/scyllaadm')
< here >
    run('useradd -o -u 1000 -g scyllaadm -s /bin/bash -d /home/scyllaadm centos')
    if distro == 'ubuntu':
        run('useradd -o -u 1000 -g scyllaadm -s /bin/bash -d /home/scyllaadm ubuntu')
```

We are copying files and we need to change the permissions `chown -R scyllaadm:scyllaadm /home/scyllaadm`

### PR DESCRIPTION
**Pull request by syuu1228**
dot files should be owned by user, so chown them.

Fixes #125

### CODE REVIEW

**Comment by slivne** [comment]
@syuu1228 you closed the pull request was does that mean ?

**Comment by eliransin** [comment]
@syuu1228 ping

**Comment by syuu1228** [comment]
@slivne I closed it once because the script has compatibility issue, could not run in CentOS7 AMI.
Just pushed fixed version and reopen the issue.

**Comment by syuu1228** [comment]
Note: the bug on previous version was using Python3 API in CentOS7 AMI.
This script does trick to run on both Python2 and Python3, need to compatible with both versions.

**Review by penberg — APPROVED** [review]
Looks good.

Would be good to extract the UID and GID magic numbers to constants as a follow up.

**Comment by syuu1228** [comment]
ping

**Comment by syuu1228** [comment]
ping

**Comment by syuu1228** [comment]
ping

**Comment by eliransin** [comment]
@penberg @bentsi it looks like this patch slipped under your radar :slightly_smiling_face: 
I think that @syuu1228 is waiting for a review + merge from you guys.

**Pull request merged**
