### PR TITLE
cloudformation: SGCluster : Missing egress rule

### PR DESCRIPTION
**Pull request by yaronkaikov**
Missing egress rule in security group means CloudFormation will 
automatically add an outbound rule to allow all traffic outbound. Make 
this explicit by adding egress rule if it is the desired configuration. 
No need to parametize it.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#aws-properties-ec2-security-group--examples--Remove_Default_Rule

Fixes: https://github.com/scylladb/scylla-machine-image/issues/161

### CODE REVIEW

**Comment by yaronkaikov** [comment]
@penberg ping

**Comment by penberg** [comment]
If I understand the change correctly, this prevents a Scylla node from communicating with any external nodes. This means that the node will not be able to connect to other nodes in the cluster, no?

**Comment by yaronkaikov** [comment]
> If I understand the change correctly, this prevents a Scylla node from communicating with any external nodes. This means that the node will not be able to connect to other nodes in the cluster, no?

@penberg Fixed. I have created a 3 node cluster using this cloudformation. i have 3 nodes up and running , but shouldn't i see under `nodetool status` all 3 of them?
Now i see
```
$ nodetool status

Datacenter: us-east
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns    Host ID                               Rack
UN  172.31.0.11  294.2 KB   256          ?       6b440f3e-a860-48b6-9545-d5d728c58920  1a
```

**Comment by yaronkaikov** [comment]
@penberg So this is related to my change., i will figure how to fix it

**Comment by yaronkaikov** [comment]
@penberg  please review again , apparently there was a configuration issue in https://github.com/scylladb/scylla-machine-image/pull/163 which actually messed up what i was trying to do here. Added another commit fixing it and explaining

**Pull request merged**
