### PR TITLE
Introduce common APIs for cloud instance

### LINKED ISSUE #297: cloud instance classes have different APIs even doing same thing
This issue moved from https://github.com/scylladb/scylla/issues/9742 since we move cloud instance APIs to scylla-machine-image.

----

Currently, cloud instance classes does not use same method name to do same thing.
For example, we have following code to do getting additional disks for RAID: 
```
def get_default_devices(instance):
    disk_names = []
    if is_ec2():
        disk_names = instance.ephemeral_disks()
        if not disk_names:
            disk_names = instance.ebs_disks()
            check_persistent_disks_are_empty(disk_names)
    elif is_gce():
        disk_names = instance.getEphemeralOsDisks()
        if not disk_names:
            disk_names = instance.getPersistentOsDisks()
            check_persistent_disks_are_empty(disk_names)
    elif is_azure():
        disk_names = instance.getEphemeralOsDisks()
        if not disk_names:
            disk_names = instance.getPersistentOsDisks()
            check_persistent_disks_are_empty(disk_names)
```

I think we should define abstract class and add common API in it, inherit the base class from all cloud instance classes.
Looks like we can do it with ABC module:
https://docs.python.org/3.9/library/abc.html

Also maybe we should rename disk APIs as @avikivity suggested: https://github.com/scylladb/scylla/pull/9417#issuecomment-932968010
(ephemeral_disk / persistent_disk to local_data_disk / remote_data_disk)

### PR DESCRIPTION
**Pull request by syuu1228**
Currently, cloud instances classes APIs are not unified, some method
name different between clouds.
For example, getting ephemeral disks is 'ephemeral_disks()' on AWS,
but 'getEphemeralOsDisks()' on gce and azure.
To fix this, add abstract class 'cloud_instance' and make sure
common APIs and change method names to unified one.

Fixes #297

### CODE REVIEW

**Comment by syuu1228** [comment]
This PR requires scylladb/scylla#9789

**Comment by syuu1228** [comment]
I will rebase this PR with https://github.com/scylladb/scylla/pull/9789 to add API part in scylla-machine-image, after we merged scylladb/scylla-machine-image#289 (move cloud related code from scylla repository to scylla-machine-image).

**Comment by syuu1228** [comment]
Merge "common API" part (https://github.com/scylladb/scylla/pull/9789) to this PR, make it work with 4bc0664006837583d26a5354f86f0b3dd36200c3.

**Comment by syuu1228** [comment]
@yaronkaikov ping

**Comment by yaronkaikov** [comment]
@syuu1228 Did you verify it with AMI build?

**Comment by syuu1228** [comment]
> @syuu1228 Did you verify it with AMI build? 

I did verify by building AMI and launch the instance, checked scylla-image-setup.service succeeded manually.
But I haven't run test on jenkins, will do it later.

**Comment by syuu1228** [comment]
@yaronkaikov Test passed https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/next-machine-image/223/

**Review by yaronkaikov — APPROVED** [review]

**Pull request merged**
