### PR TITLE
azure_instance: add support Lasv3-series

### PR DESCRIPTION
**Pull request by syuu1228**
Adding support Lasv3-series.

Closes https://github.com/scylladb/scylla-machine-image/issues/420

### CODE REVIEW

**Comment by syuu1228** [comment]
As I reported at https://github.com/scylladb/scylla-machine-image/issues/420#issuecomment-1400226003, I couldn't test this patch on Lasv3-series because of quota.

**Comment by syuu1228** [comment]
Verified working Lasv3-series.

**Comment by yaronkaikov** [comment]
@syuu1228 Why are we adding support for this? do we have an issue or a request?

**Comment by syuu1228** [comment]
@yaronkaikov Added issue reference on commitlog and PR description.

**Review by yaronkaikov — APPROVED** [review]

**Pull request merged**
